[package]
name = "wcr"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4", features = ["derive"] }

[dev-dependencies]
anyhow = "1"
assert_cmd = "2"
predicates = "3"
rand = "0.8"
pretty_assertions = "1"
