[package]
name = "echor"
version = "0.1.0"
description = "Rust echo"
edition = "2021"

[dependencies]
clap = { version = "4", features = ["derive"] }

[dev-dependencies]
assert_cmd = "2"
predicates = "3"
