[package]
name = "calr"
version = "0.1.0"
edition = "2024"

[dependencies]
nu-ansi-term = "0.50.1"
anyhow = "1.0.79"
chrono = "0.4.34"
clap = { version = "4.5.0", features = ["derive"] }
itertools = "0.14.0"

[dev-dependencies]
assert_cmd = "2.0.13"
predicates = "3.0.4"
pretty_assertions = "1.4.0"
