[package]
name = "findr"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4", features = ["derive"] }
walkdir = "2"
regex = "1"

[dev-dependencies]
anyhow = "1"
assert_cmd = "2"
predicates = "3"
pretty_assertions = "1"
rand = "0.8"
